version: '3.8'

services:
    postgres:
        image: postgres:14
        restart: always
        ports:
            - '5432:5432'    
        volumes:
            - ./db_data/segment:/var/lib/postgresql/data
        env_file:
            - .env    
        healthcheck:
            test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
            interval: 5s
            timeout: 5s
            retries: 5
    app:
        build: 
          context: ..
          dockerfile: Dockerfile
        ports:
          - 8080:8080  
        env_file:
            - .env
        