name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:

  build-and-test:
    name: Test
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - name: Build the app
        run: make build
 
      - name: Make tests
        run: make test